#!/bin/bash
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
if [[ ! -d /etc/github ]]; then  # Memeriksa apakah folder /etc/github tidak ada
    mkdir -p /etc/github         # Membuat folder /etc/github jika tidak ada
fi

if [[ ! -e /etc/github/cf ]]; then  # Memeriksa apakah file /etc/github/cf tidak ada
    echo "4ecfe9035f4e6e60829e519bd5ee17d66954f" > /etc/github/cf  # Mengunduh dan membuat file cf jika belum ada
fi

clear
echo -e ""
echo -e "\033[96;1m============================\033[0m"
echo -e "\033[95;1m      INPUT SUBDOMAIN  \033[0m"
echo -e "\033[96;1m============================\033[0m"
echo -e "\033[91;1m Note. contoh domain :\033[0m \033[93m xxx.wanx-store.web.id\033[0m"
read -p "DOMAIN    :  " lol
echo -e " "
read -p "IP        :  " IP
echo -e ""
DO=$(echo "$lol" | cut -d "." -f2-)
SUB=$(echo "$lol" | cut -d "." -f1)
SUB_DOMAIN=${SUB}.${DO}
NS_DOMAIN=*.${SUB_DOMAIN}
CF_KEY=$(cat /etc/github/cf)
set -euo pipefail
echo "Pointing Domain for $SUB_DOMAIN..."
ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DO}&status=active" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

		RECORD1=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}' | jq -r .result.id
		)
	else
		RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}'
	)
	fi
		
	if [[ "${#RECORD1}" -le 10 ]]; then
		RECORD2=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}' | jq -r .result.id
		)
	else

	RESULT2=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD1}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}'
	)	
	fi
clear
CHATID="1486508882" 
KEY="7286072978:AAF6JRoH86zg5UAQeHKrpIviAICDc-vJxDU"
TIMES="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="_______________________________
  POINTING DOMAIN BERHASIL 
_______________________________
  DOMAIN  : $SUB_DOMAIN 
  WILCARD : $NS_DOMAIN 
  IP      : $IP 
_______________________________
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  POINTING DOMAIN BERHASIL $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
echo -e "   \e[1;32m  DOMAIN  : $SUB_DOMAIN $NC"
echo -e "   \e[1;32m  WILCARD : $NS_DOMAIN $NC"
echo -e "   \e[1;32m  IP      : $IP $NC"
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "[ ${BLUE}WARNING${NC} ] Do you want to Pointing Again ? (y/n)? "
read answer

# Memeriksa input jawaban
if [[ $answer =~ ^[Yy]$ ]]; then
    cf  # Panggil fungsi cf
else
    m-ftr  # Panggil fungsi utility
fi
