#!/bin/bash
REDBLD="\033[0m\033[91;1m"
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
NC='\e[0m'
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"
# // Gettings Info
function print_install() {
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${YELLOW} # $1 ${FONT}"
echo -e "${BLUE} =============================== ${FONT}"
sleep 1
}
function print_success() {
if [[ 0 -eq $? ]]; then
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${Green} # $1 berhasil dipasang"
echo -e "${BLUE} =============================== ${FONT}"
sleep 2
fi
}
function Rename() {
clear
echo -e "${YELLOW}----------------------------------------------------------${NC}"
echo -e "\033[96;1m                      Welcome To Script Xwan              \033[0m"
echo -e "${YELLOW}----------------------------------------------------------${NC}"
echo ""
sleep 3s
echo -e "    ----------------------------------"
echo -e "   |\e[1;32mPlease Select a Options \e[0m|"
echo -e "    ----------------------------------"
echo -e "     \e[1;32m1)\e[0m Rename Script"
echo -e "     \e[1;32m2)\e[0m Default "
echo -e "   ------------------------------------"
read -p "   Please select numbers 1-2 or Any Button(Default) : " host
echo ""
if [[ $host == "1" ]]; then
clear
echo ""
echo ""
echo -e "   \e[1;36m_______________________________$NC"
echo -e "   \e[1;32m      CHANGES NAME SCRIPT $NC"
echo -e "   \e[1;36m_______________________________$NC"
echo -e ""
read -p "   INPUT YOUR NAME :   " host1
read -p "   INPUT PAS ADMIN :   " host11
rm /etc/xray/username
if [[ $host11 == 123@Xwan ]]; then
echo $host1 >> /etc/xray/username
echo ""
clear
print_success "Rename Script"
sleep 3
menu
else
echo "PIAN STORE" > /etc/xray/username
clear
echo -e "${RED} Mohon Maaf Sepertinya Anda Bukan Owner ${NC}"
sleep 3
clear
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "             \033[0;33mContact Admin :\033[0m"
    echo -e "      \033[2;32mWhatsApp\033[0m wa.me/none"
	echo -e "      \033[2;32mTelegram\033[0m t.me/amiqyu"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 3
    print_success "Script Name Default"
    sleep 2
    menu
fi
elif [[ $host == "2" ]]; then
rm /etc/xray/username
echo "XWAN_STORE" > /etc/xray/username
clear
print_success "Script Name Default"
sleep 3
menu
fi
}
######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/awanklod/izin_new/main/ip | grep -wE $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/awanklod/izin_new/main/ip | grep -wE $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
if [[ $certifacate -le 0 ]]; then
masaaktif="EXPAIRED"
else
masaaktif="${certifacate} Day"
fi
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2

# // XWAN TUNNELING | XW PROJECT
# // WHATSAPP : 6287793583445
# // TELEGRAM : pianstore01


function Xwan_Banner() {
clear
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[96;1m│\e[0m \t \t${REDBLD}$(cat /etc/xray/username)${NC} \t \t \t  \e[96;1m│\e[0m"
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}



function Service_System_Operating() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m│\e[97m SYSTEM          : $(cat /etc/os-release | grep -w PRETTY_NAME | head -n1| sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')     \033[0m "
echo -e "\033[96;1m│\e[97m RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\033[96;1m│\e[97m UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\033[96;1m│\e[97m IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\033[96;1m│\e[97m CITY            : $(cat /etc/xray/city)    \033[0m "
echo -e "\033[96;1m│\e[97m ISP             : $(cat /etc/xray/isp)    \033[0m "
echo -e "\033[96;1m│\e[97m DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m"
}



function Service_Status() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m|\e[0m\e[33m PROXY :\e[0m $status_haproxy  \e[0m|\e[33m NGINX :\e[0m $status_nginx  \e[0m|\e[33m XRAY :\e[0m $status_xray \e[0m| $status_dropbear  \e[96;1m  | \e[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}



function Details_Clients_Name() {
echo -e "\033[96;1m   ┌───────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m   │\e[97m  VERSION     : $(cat /opt/.ver)    \033[0m "
echo -e "\033[96;1m   │\e[97m  CLIENTS     :\033[0m\033[91;1m $(cat /usr/bin/user)      \033[0m "
echo -e "\033[96;1m   │\e[97m  Expiry      :\033[0m\033[91;1m $masaaktif  \033[0m "
echo -e "\033[96;1m   └───────────────────────────────────────────┘\033[0m "
}



function Acces_Use_Command() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m│  \e[34m1.)\e[93m☞ \e[97m SSH/OPENVPN         \e[34m7.)\e[93m☞ \e[97m BOT TELEGRAM   \e[96;1m│\e[0m"   
echo -e "\033[96;1m│  \e[34m2.)\e[93m☞ \e[97m XRAY MANAGER        \e[34m8.)\e[93m☞ \e[97m UPDATE SCRIPT  \e[96;1m│\e[0m"
echo -e "\033[96;1m│  \e[34m3.)\e[93m☞ \e[97m XRAY TROJAN         \e[34m9.)\e[93m☞ \e[97m BACKUP RESTOR  \e[96;1m│\e[0m"
echo -e "\033[96;1m│  \e[34m4.)\e[93m☞ \e[97m SLOWDNS            \e[34m10.)\e[93m☞ \e[97m FEATURES       \e[96;1m│\e[0m"
echo -e "\033[96;1m│  \e[34m5.)\e[93m☞ \e[97m SADOWSOCKS         \e[34m11.)\e[93m☞ \e[97m REBOOT         \e[96;1m│\e[0m"
echo -e "\033[96;1m│  \e[34m6.)\e[93m☞ \e[97m NOOBZVPS            \e[31mx.)\e[93m☞ \e[91m EXIT           \e[96;1m│\e[0m"
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m"
}



function Select_Display() {
echo
read -p "Select From option [1/11 or x] :  " hallo
case $hallo in
1) clear ; m-ssh ;; # menu ssh
2) clear ; m-xray ;; # menu vmess
3) clear ; m-tro ;; # menu trojan
4) clear ; sd ;; # menu slowdns
5) clear ; m-ssr ;; # menu sadowsocks
6) clear ; m-noobz ;; # menu noobzvps
7) clear ; m-bot ;; # menu bot telegram
8) clear ; wget -q https://raw.githubusercontent.com/awanklod/os/main/menu/update.sh && chmod +x update.sh && ./update.sh ;; #Update script
9) clear ; m-bkp ;; # menu backup
10) clear ; m-ftr ;; # menu managers
11) clear ; reboot ;; # rebot
*) welcome ;; # Back To Home Welcome
esac
}

clear && printf '\033[3J'
#Xwan_Banner
Service_System_Operating
Service_Status
Details_Clients_Name
Acces_Use_Command
Select_Display







