#!/bin/bash
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION

y='\033[1;93m'
c="\033[0;36m"
g="\e[92;1m"
r="\033[1;31m"
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
bc="\e[5;36m"
ungu='\033[0;35m'
Green_background="\033[42;37m"
Red_background="\033[41;37m"
Suffix="\033[0m"
NC='\e[0m'
nama=$(cat /etc/xray/username)
#################
        curl -s http://myrid.my.id/token > /etc/github/api
        curl -s http://myrid.my.id/email > /etc/github/email
        curl -s http://myrid.my.id/nama > /etc/github/username
        clear
CHATID="1486508882" 
KEY="7286072978:AAF6JRoH86zg5UAQeHKrpIviAICDc-vJxDU"
TIMES="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
MYIP=$(curl -sS ipv4.icanhazip.com)
PROFIL=$(curl -sS https://raw.githubusercontent.com/awanklod/izin_new/main/ip | grep $MYIP | awk '{print $2}')
TOKEN=$(cat /etc/github/api)
REPO="https://raw.githubusercontent.com/pianstore/izinvps/"
EMAIL=$(cat /etc/github/email)
USER=$(cat /etc/github/username)
data_ip=$(curl -sS https://raw.githubusercontent.com/awanklod/izin_new/main/ip | grep $MYIP | awk '{print $6}')
checking_sc() {
if [[ -n "$data_ip" || "$data_ip" -gt 0 ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $MYIP \033[0;33mTIDAK DIIZINKAN\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "             \033[0;33mContact Admin :\033[0m"
    echo -e "      \033[2;32mWhatsApp\033[0m wa.me/none"
	echo -e "      \033[2;32mTelegram\033[0m t.me/amiqyu"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 4
exit && menu
  fi
}

function lane() {
echo -e "${bc} ————————————————————————————————————————${NC}"
}

function LOGO() {
echo -e ""
lane
echo -e "${ungu}            $nama            "
lane
echo -e ""
}

function register() {
AVAILABLE=$(curl -sS https://raw.githubusercontent.com/awanklod/izin_new/main/ip | grep $MYIP | awk '{print $6}')
echo -e "${grenbo}      $AVAILABLE ${Suffix} ${ungu} IP DAPAT ANDA REGISTER            ${Suffix}"
}

function Credit_nbstore() {
sleep 1
echo -e "" 
lane
echo -e "${ungu}      Terimakasih sudah menggunakan-"
echo -e "         Script Credit by $nama"
lane
echo -e ""
sleep 3
regisip
}

add-ip() {
    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone "${REPO}"  &> /dev/null
clear
    LOGO
    echo ""
    lane
    echo -e "MASUKAN IP VPS YANG BELUM DI DAFTAR !"
    lane
    echo -e ""
    read -p "Input IP Address : " ipqu
    CLIENT_EXISTS=$(grep -w $ipqu /root/izinvps/ipx | wc -l)
    
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
        echo "IP Already Exist !"
        exit 0
    fi

    echo -e ""
    read -p "Input Username IP (Example : NEWBIE_STORE) : " name
    echo -e ""
    read -p "Input waktu expired:" exp
clear
    exp2=`date -d "${exp} days" +"%Y-%m-%d"`
    
    # Cek apakah baris dengan # $PROFIL ada
    if grep -q "^# $PROFIL" "/root/izinvps/ipx"; then
        # Jika ada, tambahkan baris di bawahnya
        sed -i "/^# $PROFIL/a ### ${name} ${exp2} ${ipqu}" "/root/izinvps/ipx"
    else
        # Jika tidak ada, tambahkan baris baru ke akhir file
        echo -e "# $PROFIL\n### ${name} ${exp2} ${ipqu}" >> "/root/izinvps/ipx"
    fi

    exp1=$(grep "$MYIP" /root/izinvps/ipx | cut -d " " -f3)
    JUMLAH=$(grep "$MYIP" /root/izinvps/ipx | cut -d " " -f6)

    # Kurangi JUMLAH dengan 1 dan simpan hasilnya di variabel SISA
    SISA=$((JUMLAH - 1))

    # Gunakan sed untuk mengganti baris sesuai dengan format yang diberikan
    sed -i "s/### $PROFIL $exp1 $MYIP ON $JUMLAH VIP/### $PROFIL $exp1 $MYIP ON $SISA VIP/" /root/izinvps/ipx

    cd /root/izinvps
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m izin &> /dev/null
    git branch -M ipuk &> /dev/null
    git remote add origin https://github.com/${USER}/izin.git
    git push -f https://${TOKEN}@github.com/${USER}/izin.git
    cd 
 rm -rf /root/izinvps
clear
    CHATIDD="$CHATIDD"
    CHATID="$CHATID"
    KEY="$KEY"
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
    <code>───────────────────────────</code>
    <code>   SUCCESS REGISTERED IP VPS</code>
    <code>───────────────────────────</code>
    <code>USERNAME       : $name</code>
    <code>IP Address     : $ipqu</code>
    <code>Registered On  : $today</code>
    <code>Expired On     : $exp2</code>
    <code>───────────────────────────</code>
    "
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
    lane
    echo -e "${g}         SUCCESS ADD IP VPS      $NC"
    lane
    echo -e "${y}  USERNAME   :${NC}${yell} $name ${NC}"
    echo -e "${y}  IP ADDRESS :${NC}${yell} $ipqu ${NC}"
    echo -e "${y}  REGISTERED :${NC}${yell} $today ${NC}"
    echo -e "${y}  EXPIRED ON :${NC}${yell} $exp2 ${NC}"
    lane
    Credit_nbstore
}

del-ip() {
    git clone "${REPO}"  &> /dev/null
    clear
	LOGO
    echo ""
    lane
    echo -e "${g}         LIST IP VPS          $NC"
    lane
    grep -E "^###" "/root/izinvps/ipx" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    lane
	echo ""
    read -p "Input IP Address To Delete : " ipdel
    clear
    name=$(cat /root/izinvps/ipx | grep $ipdel | cut -d " " -f2)
    exp=$(cat /root/izinvps/ipx | grep $ipdel | cut -d " " -f3)
    sed -i "/^### $name $exp $ipdel/d" /root/izinvps/ipx
cd /root/izin
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m izin &> /dev/null
    git branch -M ipuk &> /dev/null
	git remote add origin https://github.com/${USER}/izin.git
	git push -f https://${TOKEN}@github.com/${USER}/izin.git
    cd 
 rm -rf /root/izinvps
    clear
CHATIDD="$CHATIDD"
CHATID="$CHATID"
KEY="$KEY"
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>───────────────────────────</code>
<code>    SUCCESS DELETE IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp</code>
<code>───────────────────────────</code>
"
#curl -s --max-time $TIME -d "chat_id=$CHATIDD&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
lane
echo -e "${g}      DONE DELETE IP VPS      $NC"
lane
echo -e "${y} USERNAME   :${NC}${yell} $name"
echo -e "${y} IP ADDRESS :${NC}${yell} $ipdel"
echo -e "${y} EXPIRED ON :${NC}${yell} $exp"
lane
Credit_nbstore
}

renew-ip() {
git clone "${REPO}"  &> /dev/null
clear
LOGO
echo ""
lane
echo -e "${g}        RENEW IP VPS      $NC"
lane
grep -E "^###" "/root/izinvps/ipx" | cut -d ' ' -f 2-6 | column -t | sort | uniq
lane
echo ""
read -p "  Input IP Address To Renew : " ipdel
read -p "  Input Days  : " days
clear
name=$(cat /root/izinvps/ipx | grep $ipdel | cut -d " " -f2)
exp=$(cat /root/izinvps/ipx | grep $ipdel | cut -d " " -f3)
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $days))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/" /root/izinvps/ipx

exp1=$(grep "$MYIP" /root/izinvps/ipx | cut -d " " -f3)
JUMLAH=$(grep "$MYIP" /root/izinvps/ipx | cut -d " " -f6)

# Kurangi JUMLAH dengan 1 dan simpan hasilnya di variabel SISA
SISA=$((JUMLAH - 1))

# Gunakan sed untuk mengganti baris sesuai dengan format yang diberikan
sed -i "s/### $PROFIL $exp1 $MYIP ON $JUMLAH VIP/### $PROFIL $exp1 $MYIP ON $SISA VIP/" /root/izinvps/ipx
cd /root/izinvps
git config --global user.email "${EMAIL}" &> /dev/null
git config --global user.name "${USER}" &> /dev/null
rm -rf .git &> /dev/null
git init &> /dev/null
git add . &> /dev/null
git commit -m izin &> /dev/null
git branch -M ipuk &> /dev/null
git remote add origin https://github.com/${USER}/izin.git
git push -f https://${TOKEN}@github.com/${USER}/izin.git &> /dev/null
cd 
 rm -rf /root/izinvps
clear
CHATIDD="$CHATIDD"
CHATID="$CHATID"
KEY="$KEY"
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>───────────────────────────</code>
<code>    SUCCESS RENEW  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
#curl -s --max-time $TIME -d "chat_id=$CHATIDD&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
echo ""
lane
echo -e "${g}         DONE RENEW IP VPS      $NC"
lane
echo -e "${y}  USERNAME   :${NC}${yell} $name"
echo -e "${y}  IP ADDRESS :${NC}${yell} $ipdel"
echo -e "${y}  EXPIRED ON :${NC}${yell} $exp4"
lane
Credit_nbstore
}
clear
checking_sc
echo ""
echo ""
echo -e "   ${BLUE}_______________________________$NC"
echo -e "   \e[1;32m  WELCOME TO REGISTER IPVPS $NC"
echo -e "   ${BLUE}_______________________________$NC"
echo ""
register
lane
echo -e " $g 1.$NC ${c}ADD IP VPS "$NC     
echo -e " $g 2.$NC ${c}DELETE IP VPS"$NC
echo -e " $g 3.$NC ${c}RENEW IP VPS"$NC
echo -e " $g 4.$NC ${c}Back To menu"$NC
lane
echo ""
read -p " Select From Options [1 - 4 or x] : " menu
case $menu in
1 | 01)

add-ip
;;
2 | 02)

del-ip
;;
3 | 03)

renew-ip
;;
4 | 04)
menu
;;
*)
exit
;;
esac
